version: '3.7'
services:
  postgres:
    image: postgres
    container_name: 'postgresdb'
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/

  posts:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8080:80'

volumes:
  database-data:
